name: Update Package semantic version
on:
  push:
    branches: ["main"]
permissions:
  actions: write
  deployments: write
  repository-projects: write

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          ref: ${{ github.head_ref }}
          fetch-depth: 0
          
      - name: Update
        uses: actions/github-script@v6
        env:
          GITHUB_TOKEN: ${{ secrets.ACTION_TOKEN }}
          GITHUB_REPOSITORY: ${{ github.repository }}
          GITHUB_REF: ${{ github.ref }}
        with:
          script: |
            const { GITHUB_TOKEN, GITHUB_REPOSITORY, GITHUB_REF } = process.env
            const semverMap = {
              feat: "minor",
              fix: "patch",
              breaking_change: "major",
              breaking: "major"
            };

            const version = semverMap[context.payload.head_commit.message.split("(")[0]];

            async function update() {
              if (version) {
                // await exec.exec(`git remote set-url origin https://x-access-token:${GITHUB_TOKEN}@github.com/${GITHUB_REPOSITORY}`)
                await exec.exec('git config --global user.name "GitHub"');
                await exec.exec('git config --global user.email "noreply@github.com"');
                // await exec.exec(`git checkout ${GITHUB_REF}`)
                await exec.exec("npm version " + version);
                await exec.exec("git status");
                // await exec.exec("git push");
              } else {
                console.log("To update package version use one of the following in your PR title:");
                console.table(semverMap);
              }
            }

            update();
      - name: check
        run: |
          git status
      - name: Push
        uses: ad-m/github-push-action@master
        with:
          branch: ${{ github.head_ref }}
          force_with_lease: true