name: Update Package semantic version
on:
  push:
    branches: ["main"]
permissions:
  actions: write
  contents: write
  deployments: write
  issues: write
  packages: write
  pull-requests: write
  repository-projects: write
  security-events: write
  statuses: write

jobs:
  semver:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          ssh-key: ${{ secrets.SSH_PRIVATE_KEY }}
          persist-credentials: true
      - name: Update
        uses: actions/github-script@v6
        with:
          script: |
            const semverMap = {
              feat: "minor",
              fix: "patch",
              breaking_change: "major",
              breaking: "major"
            };

            const version = semverMap[context.payload.head_commit.message.split("(")[0]];

            async function update() {
              if (version) {
                await exec.exec('git config --local user.name "github-actions[bot]"');
                await exec.exec('git config --local user.email "github-actions[bot]@users.noreply.github.com"');
                await exec.exec("npm version " + version);
                await exec.exec("git status");
              } else {
                console.log("To update package version use one of the following in your PR title:");
                console.table(semverMap);
              }
            }

            update();
      - name: Push
        uses: ad-m/github-push-action@master
        with:
          ssh: true
          branch: ${{ github.ref }}